name: my_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.8
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  flutter_polyline_points: ^1.0.0
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true