// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSOHL42W_-s65aA3u1b8ITm4aiHdL890w',
    appId: '1:79907331335:web:f35bff64bdc585ce7cf9a2',
    messagingSenderId: '79907331335',
    projectId: 'cafe-1ef33',
    authDomain: 'cafe-1ef33.firebaseapp.com',
    storageBucket: 'cafe-1ef33.firebasestorage.app',
    measurementId: 'G-7SGGV434GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEqvwNi5nwvOrdN7W5H9K3ujG5RP-vWts',
    appId: '1:79907331335:android:be55ec7be1cfcd127cf9a2',
    messagingSenderId: '79907331335',
    projectId: 'cafe-1ef33',
    storageBucket: 'cafe-1ef33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3fm-vbMIQhNekwZoIzk8cvO7_Vt7bwKI',
    appId: '1:79907331335:ios:376cffaee62379d67cf9a2',
    messagingSenderId: '79907331335',
    projectId: 'cafe-1ef33',
    storageBucket: 'cafe-1ef33.firebasestorage.app',
    iosBundleId: 'com.example.cafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3fm-vbMIQhNekwZoIzk8cvO7_Vt7bwKI',
    appId: '1:79907331335:ios:376cffaee62379d67cf9a2',
    messagingSenderId: '79907331335',
    projectId: 'cafe-1ef33',
    storageBucket: 'cafe-1ef33.firebasestorage.app',
    iosBundleId: 'com.example.cafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSOHL42W_-s65aA3u1b8ITm4aiHdL890w',
    appId: '1:79907331335:web:089e22edd1875b067cf9a2',
    messagingSenderId: '79907331335',
    projectId: 'cafe-1ef33',
    authDomain: 'cafe-1ef33.firebaseapp.com',
    storageBucket: 'cafe-1ef33.firebasestorage.app',
    measurementId: 'G-HKS1H8C993',
  );
}
